### ISSUE TITLE
Provide functionality for named arguments

### ISSUE THREAD

**Issue by pavlosgi** [backuity/clist#11]
I like the distinction between opt and arg, but opt allows naming them when passing them and arg does not. Could we add that for arg as well. Thank you

**Comment by backuitist** [comment]
Are you looking for this: https://github.com/backuity/clist/blob/master/tests/src/test/scala/org/backuity/clist/SingleCommandParsingTest.scala#L142 ?

**Comment by pavlosgi** [comment]
That wouldn't allow me to pass the argument using --name as it's done in
opt would it? It would just give it a name in the usage string <name>. I'd
like to be able to say --arg for args as well
On 20 Apr 2016 12:19, "Bruno Bieth" <notifications@github.com> wrote:

Are you looking for this:
https://github.com/backuity/clist/blob/master/tests/src/test/scala/org/backuity/clist/SingleCommandParsingTest.scala#L142
?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/backuity/clist/issues/11#issuecomment-212385715>

**Comment by backuitist** [comment]
Oh I see.

**Comment by backuitist** [comment]
Should be soon available on maven central as 2.1.0.
See test cases: 
* https://github.com/backuity/clist/blob/master/tests/src/test/scala/org/backuity/clist/SingleCommandParsingTest.scala#L30
* https://github.com/backuity/clist/blob/master/tests/src/test/scala/org/backuity/clist/SingleCommandParsingTest.scala#L37

**Comment by pavlosgi** [comment]
Thanks !!
