### ISSUE TITLE
Wildcard import shadows usual scala globals

### ISSUE THREAD

**Issue by chbrown** [backuity/clist#12]
The docs (README.md) recommend `import org.backuity.clist._`, which is concise, certainly, but there exists `org.backuity.clist.Console`, which breaks my existing calls to `scala.Console` such as `Console.err.println("Exiting due to Ctrl-C")`, etc.

I'm not a big fan of leading with wildcard imports, particularly in introductory documentation, but I know that everybody does it. But I think if you're going to recommend that approach, you might want to avoid shadowing anything in Scala's default imports?

Otherwise, `import org.backuity.clist.{Cli, Command, opt}` seems to be working just great!

**Comment by backuitist** [comment]
I've updated the README and released 3.0.0.
