### ISSUE TITLE
Arguments from environment or command line

### ISSUE THREAD

**Issue by pavlosgi** [backuity/clist#13]
If foo-bar argument is required and is found in environment as FOO_BAR then that should be used. If it is passed as command line argument then it should override the environment.

**Comment by backuitist** [comment]
I think we should make this behavior explicit. How about `var logLevel = opt[Boolean](useEnv = true)`?

**Comment by pavlosgi** [comment]
I agree it should be explicit. That seems ok.

**Comment by backuitist** [comment]
I won't have time in the coming days, but you're welcome to give it a try :)

**Comment by pavlosgi** [comment]
If I get as time I'll give it a go.

**Comment by l15k4** [comment]
Hey,
I would personally enforce the `default` value to stick with the current convention : 
```
var logLevel = opt[String](useEnv = true, default = "foo")
```
Ie. `default` value for non-Boolean and non-Option values is required even if `useEnv` is specified.

Otherwise it is hard to reason about it. Wdyt ?
