### ISSUE TITLE
Seems that CliMain is not included in 2.0.2

### ISSUE THREAD

**Issue by apoigne** [backuity/clist#18]
CatDemo does not work

**Comment by backuitist** [comment]
can you upgrade to the latest (3.2.0)?

**Comment by apoigne** [comment]
Yeah, CliMain is include now. But you should update the README. It states 

ibraryDependencies ++= Seq(
   "org.backuity.clist" %% "clist-core"   % "2.0.2",
   "org.backuity.clist" %% "clist-macros" % "2.0.2" % "provided")

**Comment by backuitist** [comment]
Done
