### ISSUE TITLE
Parser does not seem to work properly for repeated args

### ISSUE THREAD

**Issue by apoigne** [backuity/clist#19]
I want to have possibly same args, e.g.  "localhost 9090 localhost 9091" for a source and a target, each one read using a "arg" variable. Parser claims that the target host is missing in the example. Experiments let draw the conclusion that all args must be different.

**Comment by backuitist** [comment]
Can you add the code and the error?

**Comment by apoigne** [comment]
Code is

object streamjoin extends CliMain {

  override val description =
    """
      | ""“.stripMargin


  var sourceHost = arg[String](description = "")
  var sourcePort = opt[Int](description = "Port of the Source (default: 9092)", default = 9092)
  var sourceTopic = arg[String](description = "Source topic")
  var sourceSsl = opt[Boolean](description = "Source uses SSL", default = false)
  var targetHost = arg[String](description = "Host of the  Target")
  var targetPort = opt[Int](description = "Port of the  Target (default: 9092)", default = 9092)
  var targetTopic = arg[String](description = "Target topic")
  var targetSsl = opt[Boolean](description = "Target usest SSL (default: false)", default = false)

  implicit val timeout = Timeout(30.seconds)

  val system = ActorSystem("streamjoin")

  case class Kel(kel: String)

  def run: Unit = {
    println(
      s"""Source: ($sourceHost,$sourcePort) Topic $sourceTopic ${if (sourceSsl) "nutzt SSL" else ""},
          |Target: ($targetHost, $targetPort) Topic $targetTopic ${if (targetSsl) "nutzt SSL" else ""}
     """.stripMargin)
  }

}


Args are e.g.

 localhost xxx localhost xxx


Message is

Usage

 streamjoin [options] <sourceHost> <sourceTopic> <targetHost> <targetTopic> : 

 

Options

   --source-port=NUM : Port of the Source (default: 9092)
   --source-ssl      : Source uses SSL
   --target-port=NUM : Port of the  Target (default: 9092)
   --target-ssl      : Target usest SSL (default: false)

No argument provided for targetHost

Process finished with exit code 1

If I use "localhost xxx localhost xxx localhost xxx“ for arguments   same result

If I use l"ocalhost xxx localhost yyy localhost xxx“

it say

No argument provided for targetTopic

So it seems that every input word probably goes to a Map, hence is unique.

**Comment by backuitist** [comment]
Correct, with different args it works: "1 2 3 4".
I'll fix it soon.

**Comment by backuitist** [comment]
released as 3.2.1
thanks for the report!
