### ISSUE TITLE
Parse error description is not too informative

### ISSUE THREAD

**Issue by pyal** [backuity/clist#8]
Currently parse errors are shown as:
Unknown command 'Y1'
It will be nice to add context : what  command, arguments were found, show input command string with the error position. Why this state is treated as error

**Comment by backuitist** [comment]
I've improved this but maybe not to the extend you thought of: no error position is provided but in your case, for multiple command, it either lists all the available commands (as a reminder) or suggests something (if deemed relevant).
So I'm closing this, maybe open an other issue with the error position if you feel that's needed.
