### ISSUE TITLE
args do not show description

### ISSUE THREAD

**Issue by pyal** [backuity/clist#9]
Cannot see description for args in the command line help.
It will be nice to add rows with args names + description (may be with different from opt description color) - similar to opt description.

**Comment by backuitist** [comment]
Hi Alexey, I've added the "help wanted" labels to the issues you recently created, feel free to submit PR :)

**Comment by pyal** [comment]
ok, will try to implement ;)

**Comment by apoigne** [comment]
i have an implementation and wonder how to commit

**Comment by backuitist** [comment]
Fork the repo and then create a PR
https://help.github.com/articles/about-pull-requests/

**Comment by backuitist** [comment]
Fixed by #21
